services:
  argenplay-lobby:
    container_name: argenplay-lobby
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "25565:25565"
    depends_on:
      - database
    tty: true
    stdin_open: true
    restart: always
  database:
    image: mysql:9.4.0
    container_name: database
    env_file:
      - .env
    volumes:
      - /var/lib/mysql:/db-data
  phpmyadmin:
    image: phpmyadmin:5.2.2
    depends_on:
      - database
    container_name: pma
    env_file:
      - .env
    ports:
      - "8080:80"

volumes:
  db-data:
